name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows: ["ci.yaml", "e2e.yaml"]
    types:
      - completed
    
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'ci.yaml' && github.event.workflow_run.name == 'e2e.yaml' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
