name: Unit Tests

on:
  workflow_call:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/cache@v4
        name: Setup cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: 📦 Install deps
        run: bun install --no-frozen-lockfile

      - name: 🧪 Unit test
        run: |
          bun run test:dom
          bun run test:node
              
      - name: Uplaod unit test artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage
          if-no-files-found: ignore
